# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3d3d01e1d5f352f1f5855b3e39af23a48445984ccff14e2a23e11b91127f4741afecb0dc87c35136bfadf25f31e6e864a8f8ca42da7e060468a15f9214d5976

test:
  secret_key_base: 9ed095880a5e47aa8ecf65d8b02510d707852dbf6497f22dd1be4e05f661d4a1893c02c3565cc0cca68f6906d0b7ef72fd6d289177147d33f54f06e99b43c127

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
